name: Windows

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Stock 
    runs-on: ubuntu-latest
    steps:
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc-mingw-w64 automake autoconf make cmake ninja-build

      - name: Clone Project
        uses: actions/checkout@v4

      - name: Build
        id: autotools_build
        run: |
          ./autogen.sh
          ./configure --enable-win --build=i686-pc-linux-gnu --host=i686-w64-mingw32
          env CFLAGS="-Werror" make -j$(nproc)

      - name: Build with CMake/Ninja
        id: cmake_build
        run: |
          mkdir build
          cd build
          cmake -G Ninja \
            -DCMAKE_C_FLAGS="-Werror" \
            -DSUPPORT_WINDOWS_FRONTEND=ON \
            -DSUPPORT_BUNDLED_PNG=ON \
            -DCMAKE_TOOLCHAIN_FILE=../toolchains/linux-i686-mingw32-cross.cmake \
            ..
          ninja -j$(nproc)

  release-flags:
    runs-on: ubuntu-latest
    steps:
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc-mingw-w64 automake autoconf make

      - name: Clone Project
        uses: actions/checkout@v4

      - name: Build with Flags Used for Release
        run: |
          ./autogen.sh
          env CFLAGS="-O2" ./configure --enable-release --enable-win --build=i686-pc-linux-gnu --host=i686-w64-mingw32
          env CFLAGS="-Werror" make -j$(nproc)
